AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: custom build python-selenium-chromium-on-lambda

Globals:
  Function:
    Timeout: 60

Resources:
  PythonSeleniumChromiumOnLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 2048
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.8-v1
